
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: microservice
          uri: http://localhost:8001/microservice
          predicates:
            - Path=/microservice/**
server:
  port: 8888